/// Prompt generation for pet sprite creation.
/// Prompts are designed to be generic — they work for any character type
/// (animals, robots, humanoids, game characters, personified objects, etc.)

pub struct PetPromptConfig {
    pub pet_name: String,
    pub description: String,
    pub style_preset: String,
    pub chroma_key: String,
}

struct RowSpec {
    state: &'static str,
    frames: u32,
    action: &'static str,
    requirements: &'static str,
}

const STYLE_CONTRACTS: &[(&str, &str)] = &[
    ("3d-toy", "Stylized 3D toy character with smooth rounded forms, simple materials, clear silhouette, and no photoreal complexity."),
    ("pixel", "Crisp pixel-art sprite with limited palette, clean outlines, no anti-aliasing, and readable at small sizes."),
    ("clay", "Handcrafted clay/plasticine style with soft rounded forms, visible sculpted texture, and warm lighting."),
    ("sticker", "Flat sticker-style with bold outlines, simple fills, minimal shading, and die-cut ready edges."),
    ("plush", "Soft plush toy style with fabric texture, rounded stitched edges, button eyes, and cozy feel."),
    ("flat-vector", "Clean flat vector style with geometric shapes, limited palette, no gradients, and sharp edges."),
];

const ROW_SPECS: &[RowSpec] = &[
    RowSpec {
        state: "idle",
        frames: 6,
        action: "Calm resting loop: subtle breathing, tiny blink, slight body bob, and only quiet motion.",
        requirements: "- CRITICAL: idle is the baseline state; the first frame is also the static reduced-motion sprite.\n- Use only subtle idle motion: gentle breathing, a tiny blink, a slight head or body bob.\n- Keep the character in the same pose, facing direction, silhouette, markings, palette, and props across all 6 frames.\n- Idle must be calm but still read as animation; do not repeat identical frames.\n- Do not show waving, walking, running, jumping, talking, working, reviewing, emotional reactions, or large gestures.\n- The first and last frames should be nearly identical so the loop feels smooth.",
    },
    RowSpec {
        state: "running-right",
        frames: 8,
        action: "Dragging-right loop: show directional movement to the right through body and limb poses only.",
        requirements: "- Show directional drag movement to the right through body and limb poses.\n- The character must unmistakably face and travel right.\n- Movement cadence must alternate visibly across the 8 frames.\n- Do not draw speed lines, dust clouds, floor shadows, motion trails, or detached effects.",
    },
    RowSpec {
        state: "running-left",
        frames: 8,
        action: "Dragging-left loop: mirror of running-right.",
        requirements: "- This row is generated by mirroring running-right.",
    },
    RowSpec {
        state: "waving",
        frames: 4,
        action: "Greeting loop: limb or appendage down, raised, tilted, and returning in a friendly gesture.",
        requirements: "- Show the greeting through limb, hand, wing, tentacle, or appendage pose only.\n- The waving motion should be clear and friendly.\n- Do not draw wave marks, motion arcs, sparkles, symbols, or floating effects.",
    },
    RowSpec {
        state: "jumping",
        frames: 5,
        action: "Hover jump loop: anticipation crouch, lift, airborne peak, descent, and settle.",
        requirements: "- Show jump through vertical position change: the character rises and falls.\n- Peak frame should have the character noticeably higher than the base.\n- Do not draw ground shadows, contact shadows, dust, smears, or motion marks.\n- Keep the background perfectly flat chroma key with no darker patches.",
    },
    RowSpec {
        state: "failed",
        frames: 8,
        action: "Blocked/failed loop: slumped or deflated reaction with sad expression.",
        requirements: "- Show failure through slumped pose, drooping parts, closed or sad eyes, and lower body position.\n- Small tears, smoke puffs, or tiny stars are allowed only if attached to the character silhouette.\n- Do not draw red X marks, floating symbols, detached effects, or loose particles.",
    },
    RowSpec {
        state: "waiting",
        frames: 6,
        action: "Needs-input loop: expectant asking pose, looking around, slight fidget, anticipating interaction.",
        requirements: "- Show that the character needs input through an expectant pose: looking up, tilting head, small shifts.\n- Must be distinguishable from idle (more alert, expectant).\n- Keep the motion patient and readable.\n- Do not draw clocks, question marks, thought bubbles, or floating symbols.",
    },
    RowSpec {
        state: "running",
        frames: 6,
        action: "Working/processing loop: focused activity showing active task execution — NOT literal running or jogging.",
        requirements: "- Show the character actively working or processing: focused posture, busy hands/limbs, purposeful bobbing, thinking motion, or other non-locomotion activity.\n- This represents 'executing a task', NOT literal foot-running, jogging, sprinting, or any locomotion.\n- Do not show running legs, raised knees, pumping arms, directional travel, speed lines, dust clouds, or treadmill motion.\n- Must be distinguishable from idle (more energetic, purposeful) and review (not inspecting).",
    },
    RowSpec {
        state: "review",
        frames: 6,
        action: "Ready-review loop: focused inspection with lean, narrowed eyes, head tilt, or examining pose.",
        requirements: "- Show review through lean, narrowed eyes, head tilt, or examining posture.\n- Must be distinguishable from waiting (reviewing is inspecting, not anticipating).\n- Do not add magnifying glasses, papers, code, UI, or new props not in the base design.",
    },
];

impl PetPromptConfig {
    fn style_contract(&self) -> String {
        let base = "Desktop companion sprite: compact full-body character, readable in a 192x208 cell, clear silhouette, and crisp edges for chroma-key extraction.";
        let preset_desc = STYLE_CONTRACTS
            .iter()
            .find(|(k, _)| *k == self.style_preset)
            .map(|(_, v)| *v)
            .unwrap_or(STYLE_CONTRACTS[0].1);
        format!("{base} Style `{}`: {preset_desc}", self.style_preset)
    }
}

pub fn build_base_prompt(config: &PetPromptConfig) -> String {
    let style_contract = config.style_contract();
    format!(
        r#"Create one clean full-body reference sprite for a desktop companion named "{name}".

Character identity: {description}
Style: {style_contract}

IMPORTANT: Preserve the original character type exactly as described. Do NOT transform the character into a cat, animal, or any creature unless explicitly described as one. If the character is a robot, keep it a robot. If it is a humanoid, keep it humanoid. If it is an object, keep it as that object. If it is an animal, keep it as an animal.

Place a single centered pose on a perfectly flat pure {chroma} chroma-key background. Keep the full character visible, compact, readable at 192x208, and easy to animate. No scenery, text, borders, checkerboard transparency, shadows, glows, detached effects, or extra props. Keep {chroma} and close colors out of the character body."#,
        name = config.pet_name,
        description = config.description,
        style_contract = style_contract,
        chroma = config.chroma_key,
    )
}

pub fn build_row_prompt(config: &PetPromptConfig, row_index: usize) -> String {
    let spec = &ROW_SPECS[row_index];
    let style_contract = config.style_contract();
    format!(
        r#"Create one horizontal animation strip for desktop companion "{name}", state `{state}`.

Use the attached canonical base for identity. Use the attached layout guide only for slot count, spacing, centering, and padding; do not draw the guide.

Output exactly {frames} full-body frames in one left-to-right row on flat pure {chroma}. Treat the row as {frames} invisible equal-width slots: one centered complete pose per slot, evenly spaced, with no overlap, clipping, empty slots, labels, or borders.

IMPORTANT - Character preservation: Keep the EXACT same character type from the base image. Do NOT transform it into a cat, animal, or any other creature type. A robot stays a robot. A humanoid stays humanoid. An animal stays an animal. An object stays an object. Preserve silhouette, face, proportions, markings, palette, material, style, and all identifying features across every frame.

Identity: same character in every frame: {description}
Style: {style_contract}
Animation continuity: keep apparent character scale and baseline stable within the row unless the state intentionally changes vertical position (like `jumping`). Move the pose within the slot instead of redrawing the character larger or smaller frame to frame.

State action: {action}

State requirements:
{requirements}

Clean extraction: crisp opaque edges, safe padding, no scenery, text, guide marks, checkerboard, shadows, glows, motion blur, speed lines, dust, detached effects, stray pixels, or chroma-key colors inside the character."#,
        name = config.pet_name,
        state = spec.state,
        frames = spec.frames,
        chroma = config.chroma_key,
        description = config.description,
        style_contract = style_contract,
        action = spec.action,
        requirements = spec.requirements,
    )
}

/// Build prompt for a BATCH of frames within a row (for splitting wide strips).
pub fn build_batch_prompt(config: &PetPromptConfig, row_index: usize, batch_frames: u32, batch_start: u32, total_frames: u32) -> String {
    let spec = &ROW_SPECS[row_index];
    let style_contract = config.style_contract();
    let continuity_note = if batch_start == 0 {
        format!("This is the beginning of the animation (frames 1-{} of {}).", batch_frames, total_frames)
    } else {
        format!("This continues the animation (frames {}-{} of {}). Maintain the same pose progression as if extending the previous frames.", batch_start + 1, batch_start + batch_frames, total_frames)
    };
    format!(
        r#"Create one horizontal animation strip for desktop companion "{name}", state `{state}`.

Use the attached canonical base for identity. Use the attached layout guide only for slot count, spacing, centering, and padding; do not draw the guide.

Output exactly {batch_frames} full-body frames in one left-to-right row on flat pure {chroma}. Treat the row as {batch_frames} invisible equal-width slots: one centered complete pose per slot, evenly spaced, with no overlap, clipping, empty slots, labels, or borders.

{continuity_note}

IMPORTANT - Character preservation: Keep the EXACT same character type from the base image. Do NOT transform it into a cat, animal, or any other creature type. Preserve silhouette, face, proportions, markings, palette, material, style, and all identifying features across every frame.

Identity: same character in every frame: {description}
Style: {style_contract}
Animation continuity: keep apparent character scale and baseline stable within the row unless the state intentionally changes vertical position (like `jumping`). Move the pose within the slot instead of redrawing the character larger or smaller frame to frame.

State action: {action}

State requirements:
{requirements}

Clean extraction: crisp opaque edges, safe padding, no scenery, text, guide marks, checkerboard, shadows, glows, motion blur, speed lines, dust, detached effects, stray pixels, or chroma-key colors inside the character."#,
        name = config.pet_name,
        state = spec.state,
        batch_frames = batch_frames,
        chroma = config.chroma_key,
        continuity_note = continuity_note,
        description = config.description,
        style_contract = style_contract,
        action = spec.action,
        requirements = spec.requirements,
    )
}

pub fn row_count() -> usize {
    ROW_SPECS.len()
}

pub fn row_state_name(index: usize) -> &'static str {
    ROW_SPECS[index].state
}

pub fn row_frame_count(index: usize) -> u32 {
    ROW_SPECS[index].frames
}
